import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import UseProvider from "./(Model)/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "시설시설 V2",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="ko">
            <head>
                <link
                    rel="manifest"
                    href="/manifest.json"
                ></link>
            </head>
            <UseProvider>
                <body className={inter.className}>
                    {children}
                </body>
            </UseProvider>
        </html>
    );
}
